name: Deploy docker image

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.103'
    - run: make build-backend
      name: Build
    - run: make test-backend
      name: Test
    - name: Setup Elm
      uses: jorelali/setup-elm@v2
    - run: make prepare-image
      name: Prepares backend & frontend into an image
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: softwarepark/contexture
        workdir: artifacts/image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
